name: docker-backend-cud
services:
- name: docker-backend-cud
  envs:
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  github:
    branch: master
    deploy_on_push: false
    repo: reitansora/docker-backend-cud