name: Digital Ocean Deploy on Pull Request Merged

on:
  pull_request:
    branches: [master]
    types: [closed]
  push: 
    branches: [master]

jobs:
  verify:
    name: Check whether a pull request has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - 
        name: Success Message
        run: echo "🎉 A pull request is merge by ${{ github.event.pull_request.merged_by }}"

  deploy:
    needs: [verify]
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest
    steps:
      - 
        name: Deploy
        uses: inspire-labs-tms-tech/digital-ocean-deploy-action@2.0.2
        with:
          app-id: ${{ secrets.DO_APP_ID }}
          api-key: ${{ secrets.DO_API_KEY }}
          force: "true"
  
  docker:
    needs: [verify]
    name: Build container image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest